# Generated by Django 2.2.7 on 2024-03-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haircuts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haircut',
            name='person',
        ),
    ]
