# Generated by Django 2.2.7 on 2024-02-27 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircuts', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='haircut',
            name='cutside1',
            field=models.ImageField(blank=True, upload_to='cuts/'),
        ),
        migrations.AddField(
            model_name='haircut',
            name='cutside2',
            field=models.ImageField(blank=True, upload_to='cuts/'),
        ),
        migrations.AddField(
            model_name='haircut',
            name='cutside3',
            field=models.ImageField(blank=True, upload_to='cuts/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
