# Generated by Django 2.2.7 on 2024-03-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircuts', '0003_auto_20240227_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haircut',
            name='date',
            field=models.DateField(),
        ),
    ]
