# Generated by Django 2.2.7 on 2024-04-02 06:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haircuts', '0004_remove_haircut_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='haircut',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='haircut',
            name='barber',
            field=models.CharField(default='balu bhai', max_length=200),
        ),
        migrations.AlterField(
            model_name='haircut',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
